### ISSUE TITLE
Broken in 0.10.4

### ISSUE THREAD

**Issue by PatrickTulskie** [tzcl/logseq-monokai#1]
Not sure if this is something that can be addressed by the theme or if it's an issue with Logseq, but it looks like in 0.10.4, this theme is essentially unreadable. Reverting to 0.10.3 makes things functional again.

**Comment by tzcl** [comment]
Thanks, I just noticed this too. Looks like there's major UI changes in 0.10.4 I'll need to investigate.

**Comment by PatrickTulskie** [comment]
Okay yeah kinda weird for a patch release. I guess they don't do semver. Thanks for looking into it.

**Comment by ssasoglu** [comment]
I can confirm that issue persists in Logseq version 0.10.5.

**Comment by eXConf** [comment]
Setting up an accent color in the app settings can be used as workaround for now, as mentioned in [LogSeq issue comment](https://github.com/logseq/logseq/issues/10873#issuecomment-1897882037). Worked for me.

**Comment by PixelTux** [comment]
I've open a Pull request that should fix most of the issues up to Logseq v0.10.7.

**Comment by tzcl** [comment]
This should be resolved now in #4 😄
