### ISSUE TITLE
Missing <mark> tag for highlighting

### ISSUE THREAD

**Issue by PixelTux** [tzcl/logseq-monokai#2]
When changing the **Accenture color** from dark text or _'no color'_ to light text, the highlighter color disperses and the text loses its highlighting. 
The issue is do probably to the fact that _"Choosing an accent color may override any theme you have selected."_
difference between _'no color'_ and  _Logseq classical color_
![Screenshot from 2024-03-11 20-03-21](https://github.com/tzcl/logseq-monokai/assets/66007913/106f5da6-040d-45f5-84a7-f9514a2fd116) ![Screenshot from 2024-03-11 20-04-31](https://github.com/tzcl/logseq-monokai/assets/66007913/c6992195-667d-4067-9083-6cf10ea802aa)

I believe that this issue could be address by specifically targeting the `<mark>` tag.
Logseq v0.10.7

**Comment by PixelTux** [comment]
The issue has been resolved. I've utilized the --yellow color for the background and --base2 for the text.
![Screenshot from 2024-03-11 20-31-47](https://github.com/tzcl/logseq-monokai/assets/66007913/10aec64d-0778-4326-9990-6055c3c3bf54)

This solution is compatible with all Accenture colors in Logseq v0.10.7.
commit [1992081](https://github.com/tzcl/logseq-monokai/commit/1992081d7a8aa4a1defe1858ef6689bfbd616723)
[Pull requests](https://github.com/tzcl/logseq-monokai/pull/3)

**Comment by tzcl** [comment]
Resolved in #4
